name: Keep Supabase Active

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Send API Request to Supabase
        run: |
          curl -X POST "https://dbcaedilyjrhaiqkcpfw.supabase.co/rest/v1/rpc/keep_alive" \
            -H "apikey: SUPABASE_SERVICE_ROLE_KEY" \
            -H "Content-Type: application/json" \
            --data '{}'
