name: Keep Supabase Active

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes

jobs:
  keep-supabase-awake:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Function
        run: |
          curl -X POST "${{ secrets.SUPABASE_URL }}/rest/v1/rpc/keep_alive" \
            -H "apikey: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Content-Type: application/json" \
            --data '{}'
