name: Ping Supabase to Prevent Pausing

on:
  schedule:
    - cron: '13 9 * * 2' # Runs at 9:00 AM every Monday and Thursday '0 9 * * 1,4'

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to Supabase
        run: curl -s "https://https://dbcaedilyjrhaiqkcpfw.supabase.co/rest/v1/notices"
