name: Ping Supabase to Prevent Pausing

on:
  schedule:
    - cron: '0 9 * * 1,4' # Runs at 9:00 AM every Monday and Thursday
  workflow_dispatch:
  
jobs:
 ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase
        run: |
          curl -X GET 'https://dbcaedilyjrhaiqkcpfw.supabase.co/rest/v1/' \
          -H "apikey: ${{ secrets.SUPABASE_API_KEY }}"
