name: Ping Supabase to Prevent Pausing

on:
  schedule:
    - cron: '0 9 * * 1,4' # Runs at 9:00 AM every Monday and Thursday
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      environment:
        description: 'Environment to deploy'
        required: false
        default: 'staging'

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to Supabase
        run: curl -s "https://https://dbcaedilyjrhaiqkcpfw.supabase.co/rest/v1/notices"
